language: node_js
node_js:
- '8.0'
before_deploy:
- npm run changelog
deploy:
- provider: npm
  email: remcohaszing@gmail.com
  api_key:
    secure: Ez1VXMsPlS9gHGMHSH/Az0t34LpLmkasvjIyJnJAcHoh+zxePZ051Qe5IPH0u2JeJHEgM7iklirDxFzcwMGeCRTJ/9QbVjzGedouwmcW3hOkBCNyG9SwmTu93CAILmYasOWjML2M5TA8SoPJV/5HQY+in5THsQ41ayH8zKbU384kLFICUvNuq5dzIW78V5/SrAV5bQOTQl/mDg4Qq0qnNUOhLLVNwtIZm5aBKLGc/98drgaP6w20P/Eq5QPaHz6eHqmamUBTm0aLmrDno+8s2j7xwqgy21nSBG5Szyr3ipNg+ihgjkH7WQSKCqMo/ODmG8w+vwLa6TYJNpi8ZJzfeJ/7UwxdWRl71/OMBHE0OMwARGk2i/mzA5O67iLQBXHaZ8hz4UxgE+3AAKZbvIRjspjuODkKel28QwPfaI8snXsagDDEFWAy1/ZrkvYspkO5dxBn2CdurKyFlso25SHvaeF7m2/MKRn/NB4CHPre1R8z1YiHB2Z1R71eOwbn0BG2kbzR55UuBAB2htEWHKFbpRtsQqtED9xE2Tra6n+rZH4DAnVp8NpoU5d5UXYIsn936UV2BpZ3OkFNnoMs6AwV2D/iZdOArtG3G7DBOHM2fYsmsJNVX51cKWdgNWECq8TahkRoksOwMl+u4ktGsRGa2EhmcMLlEaF9Itdm7jklnPs=
  on:
    tags: true
    repo: appsemble/material-ui-pull-to-refresh
# - provider: releases
#   api_key:
#     secure: ROhxsKKujef8odL2deyDhdLMyjxjXFe7hG1KrL5SabUcV/7Hz6ZibvNnPQC2Dy39XBL4TwlO70/+zl4TSSSaf+lC/XbpN9TcFJZed6Jh66dQ+1/DNZYprB1sgI/oRwvaaDip0+bTEEgLgE+oRzKsbuwchJaXu768q9Iv7AXR3XS1z+O9g2zhzpXkypeSZOqhGmjqy9VO3ILGc/Qtt21a3yf1FdktocYjYmX7ircZcbjZSY66ugCPy0cBlFMjIpnnpTAmUdSuGqViW8zVk3e+ARzVC+fIQoBP4itACo4KtzKpzsisIis3j9GHBqotWitAd1oVKdeH2EPDZGJsio3Q+3Vg+SHIfLF0sv76wZMCIPG9qECCtQitzdZ/wGm0we5n9BkkZmsKlHS/HdtDX9izJZUr+TZNs6XzU513ewUXyfaIz5uGg+vfMXSAUIlKEfPTxAlTpOdvp175jcB0nbji798uWCCGby/LKkflU/hEygSthjAA+AJL1dIsxA9vB4ln2R2MGGLB3u9gARWOiG/4saGrkmj73KH7p8Z4Bdf6mWL+dS41YfDMooRs2PXsv+/osuqvnjHXrdY5iFIa1JvfiHjBkBO1Uu+JeT+xc0M5pF1AaYYjj5whJQcIR4KcmDhnHBTLkcuZoBq4r6FP7Ce/BN0MuEk1Nvog2UuRiuU3Ssc=
#   file: CHANGELOG.md
#   skip_cleanup: true
#   on:
#     tags: true
#     repo: appsemble/material-ui-pull-to-refresh
